# Numpy
- convert a list,tuple,dict in to Numpy array
- How to generate array with in a range of values
        - arrange
        - linspace
        - random.randint
- basic arthimeic operators on numpy array    

In [2]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# how to slicinng
print(a[1:10])
print(a[1:5:2])
print(a[:])

[1 2 3 4 5 6 7 8 9]
[1 3]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [5]:
# fancy indexing or boolean indexing
print(a[a>5])

[6 7 8 9]


In [6]:
a.shape

(10,)

In [7]:
a.ndim

1

In [8]:
a2=np.random.randint(10,30,(3,3))
a2

array([[18, 11, 14],
       [29, 20, 29],
       [13, 28, 23]])

In [9]:
print(a2.ndim)
print(a2.shape)

2
(3, 3)


In [10]:
for i in a2:
    print(i)
    break

[18 11 14]


In [11]:
for i in a2:
    for j in i:
        print(j,end=' ')
    print()    

18 11 14 
29 20 29 
13 28 23 


In [12]:
print(a2[0],type(a2[0]))

[18 11 14] <class 'numpy.ndarray'>


In [13]:
print(a2[0],type(a2[0]),a2[0].shape)

[18 11 14] <class 'numpy.ndarray'> (3,)


In [14]:
print(a2[1:],type(a2[1:]))

[[29 20 29]
 [13 28 23]] <class 'numpy.ndarray'>


In [15]:
print(a2[1:],type(a2[1:]),a2[1:].shape)

[[29 20 29]
 [13 28 23]] <class 'numpy.ndarray'> (2, 3)


In [16]:
# row from 0 to 2
# columns from 0 to 2
# 1st row and second column
print(a2[1][2])
print(a2[1,2])

29
29


In [17]:
print(a2[1:3,0:2])

[[29 20]
 [13 28]]


In [18]:
print(a2)

[[18 11 14]
 [29 20 29]
 [13 28 23]]


In [19]:
a3 = np.random.randint(10,100,(5,5,3))
a3

array([[[87, 68, 30],
        [18, 69, 39],
        [31, 77, 69],
        [57, 37, 43],
        [86, 87, 31]],

       [[10, 41, 69],
        [57, 60, 63],
        [65, 87, 51],
        [92, 47, 22],
        [47, 16, 80]],

       [[52, 49, 85],
        [57, 60, 22],
        [14, 42, 89],
        [74, 76, 37],
        [45, 91, 52]],

       [[36, 91, 87],
        [29, 77, 80],
        [39, 28, 50],
        [11, 16, 56],
        [21, 74, 69]],

       [[63, 88, 63],
        [80, 90, 48],
        [88, 95, 77],
        [42, 79, 56],
        [54, 97, 73]]])

In [20]:
print(a3[:2]) # indices 0,1

[[[87 68 30]
  [18 69 39]
  [31 77 69]
  [57 37 43]
  [86 87 31]]

 [[10 41 69]
  [57 60 63]
  [65 87 51]
  [92 47 22]
  [47 16 80]]]


In [21]:
print(a3[1::2])

[[[10 41 69]
  [57 60 63]
  [65 87 51]
  [92 47 22]
  [47 16 80]]

 [[36 91 87]
  [29 77 80]
  [39 28 50]
  [11 16 56]
  [21 74 69]]]


In [22]:
print(a3[1::2,2])

[[65 87 51]
 [39 28 50]]


In [23]:
print(a3[1::2,0:5:2])

[[[10 41 69]
  [65 87 51]
  [47 16 80]]

 [[36 91 87]
  [39 28 50]
  [21 74 69]]]


In [24]:
print(a3[1::2,0:5:2,2])

[[69 51 80]
 [87 50 69]]


In [25]:
a3==86

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [ True, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])

In [31]:
# boolean indexing
a3[a3==86]

array([86])

In [32]:
a3[a3>50]

array([87, 68, 69, 77, 69, 57, 86, 87, 69, 57, 60, 63, 65, 87, 51, 92, 80,
       52, 85, 57, 60, 89, 74, 76, 91, 52, 91, 87, 77, 80, 56, 74, 69, 63,
       88, 63, 80, 90, 88, 95, 77, 79, 56, 54, 97, 73])

In [33]:
a3[(a3>50) & (a3<70)] #or -- |

array([68, 69, 69, 57, 69, 57, 60, 63, 65, 51, 52, 57, 60, 52, 56, 69, 63,
       63, 56, 54])

In [34]:
a3[(a3>50) and (a3<70)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [35]:
a3[(a3<50) | (a3>70)]

array([87, 30, 18, 39, 31, 77, 37, 43, 86, 87, 31, 10, 41, 87, 92, 47, 22,
       47, 16, 80, 49, 85, 22, 14, 42, 89, 74, 76, 37, 45, 91, 36, 91, 87,
       29, 77, 80, 39, 28, 11, 16, 21, 74, 88, 80, 90, 48, 88, 95, 77, 42,
       79, 97, 73])

In [ ]:
L = list(range(100))
# 0,1,2,3--- L[:]
# 1,2,3,4.... L[1:]
# 1,3,5,7,9,11,13 #L[1::2]
# 1,13,45,74,23,67 #

In [37]:
L[[1,13,45,74,23,67]]

TypeError: list indices must be integers or slices, not list

In [38]:
aL = np.array(L)
aL[[1,13,45,74,23,67]]

array([ 1, 13, 45, 74, 23, 67])

In [39]:
aL[[45,74,23,67,1,7,3]]

array([45, 74, 23, 67,  1,  7,  3])

In [40]:
a2

array([[18, 11, 14],
       [29, 20, 29],
       [13, 28, 23]])

In [41]:
a2[[1,2],[0,1]] # (1,0)(2,1)

array([29, 28])

In [42]:
a3[[1,2],[1,2],[1,2]]#(1,1,1)(2,2,2)

array([60, 89])

In [43]:
print(a3[[1,2],[1,2],[1,2]])#(1,1,1)(2,2,2)
print(a3[1,1,1])
print(a3[2,2,2])

[60 89]
60
89


## statistical Functions

In [48]:
a = np.random.randint(20,30,5)
a


array([29, 28, 28, 22, 21])

In [49]:
print(np.mean(a))# avg
print(np.sum(a)/np.size(a))

25.6
25.6


In [50]:
# sorted a [23,24,25,27,29]
np.median(a)

28.0

In [51]:
print(np.quantile(a,0.25)) # Q1
print(np.quantile(a,0.5)) # Q2
print(np.quantile(a,0.75)) # Q3

22.0
28.0
28.0


## Logorithemic and Exponential

In [52]:
np.log(2) # log with base e

0.6931471805599453

In [53]:
np.log2(2)

1.0

In [54]:
print(np.log(2))# log with base e
print(np.log(np.exp(1)))

0.6931471805599453
1.0


In [55]:
print(np.log2(2))
print(np.log10(5))

1.0
0.6989700043360189


In [56]:
import numpy as np
print(np.log(2))# log with base e
print(np.log(np.exp(1)))

0.6931471805599453
1.0


In [57]:
print(np.log2(2))
print(np.log2(7))
print(np.log10(5))

1.0
2.807354922057604
0.6989700043360189


In [61]:
# np.log(0)
# np.log2(0)
# np.log10(0)

C:\Users\INDIA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
C:\Users\INDIA\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log2
  
C:\Users\INDIA\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log10
  This is separate from the ipykernel package so we can avoid doing imports until


-inf

In [62]:
np.log(0+1)

0.0

In [63]:
print(np.log1p(2)) # np.log(1+2)
print(np.log1p(0)) # np.log(1+0)

1.0986122886681098
0.0


In [64]:
np.exp(1)

2.718281828459045

In [65]:
np.exp(2)

7.38905609893065

In [66]:
print(np.exp2(4))#2**4

16.0


In [67]:
print(np.expm1(2))# np.exp(2)-1
print(np.exp(2)-1)

6.38905609893065
6.38905609893065
