### Import numpy as np and print the version number.

In [1]:
import numpy as np
np.__version__

'1.16.5'

### Create a 1D array of numbers from 0 to 9

In [2]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


### Create a 3×3 numpy array of all True’s

In [3]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.zeros((3,3),dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

#### Extract all odd numbers from arr

In [5]:
l=np.arange(20)
print(l)
print(type(l))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [6]:
for i in l:
    if i%2!=0:
        print(i)
    else:
        pass

1
3
5
7
9
11
13
15
17
19


### Replace all odd numbers in arr with -1

In [7]:
for i in l:
    if i%2!=0:
        l[i]=-1
    else:
        pass
print(l)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


### Convert a 1D array to a 2D array with 2 rows

In [8]:
a=np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [9]:
b=np.reshape(a,(2,-1))
print(b)
np.ndim(b)

[[1 2 3 4]
 [5 6 7 8]]


2

### Stack arrays a and b vertically


In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
np.vstack(a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
np.vstack(b)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### Stack the arrays a and b horizontally.

In [13]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
np.hstack(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.hstack(b)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Get the positions where elements of a and b match
    Input:
        a = np.array([1,2,3,2,3,4,3,4,5,6])
        b = np.array([7,2,10,2,7,4,9,4,9,8])

In [16]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a)
print(b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


### Get all items between 5 and 10 from a.
    Input:
    a = np.array([2, 6, 1, 9, 10, 3, 27])

In [18]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)

[ 2  6  1  9 10  3 27]


In [ ]:
Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

### swap columns 1 and 2 in the array arr.
    arr = np.arange(9).reshape(3,3)
    arr</pre


In [29]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[0,1]]=arr[:,[1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


### How to reverse the rows of a 2D array?
    arr = np.arange(9).reshape(3,3)
    arr</pre

In [30]:
arr = np.arange(9).reshape(3,3)
print(arr)
np.flip(arr,axis=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### Reverse the columns of a 2D array arr.
    arr = np.arange(9).reshape(3,3)
    arr

In [31]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr.T

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

### Write a NumPy program to generate five random numbers from the normal distribution

In [19]:
a=np.random.normal(size=5) # from normal distribution 
print(a)

[-0.21399079  0.87758775 -1.54249173 -1.13628726 -1.06641098]


#### Write a NumPy program to generate six random integers between 10 and 30

In [20]:
b=np.random.randint(10,30,size=6)
print(b)

[14 21 29 20 14 15]


#### Write a NumPy program to create a 3x3x3 array with random values

In [21]:

x=np.random.random((3,3,3))
print(x)

[[[0.35755284 0.19504524 0.06501362]
  [0.72136708 0.11389112 0.30333835]
  [0.45267783 0.41205639 0.87402302]]

 [[0.93964777 0.25465371 0.92362916]
  [0.05607209 0.30514807 0.95353195]
  [0.1457918  0.84528799 0.30595727]]

 [[0.11660896 0.17429338 0.25263171]
  [0.21541054 0.38190931 0.52793087]
  [0.33939252 0.01527899 0.53534295]]]


#### Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [22]:
s=np.random.random((5,5))
print(s)

[[0.46778825 0.43813727 0.24543412 0.59608075 0.26912758]
 [0.85624498 0.74130565 0.78205552 0.28503785 0.47465156]
 [0.73463646 0.76449727 0.73901975 0.93777014 0.57819781]
 [0.47109784 0.35518787 0.04981672 0.23751289 0.92664172]
 [0.08084146 0.68977456 0.60678643 0.51856097 0.73776039]]


In [23]:
np.max(s)

0.9377701438635568

In [24]:

np.min(s)

0.049816719203126913

##### Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

In [25]:
a=np.random.random((10,4))
print(a)

[[0.41069897 0.71261642 0.61297788 0.5940692 ]
 [0.60379663 0.21418231 0.9602965  0.65555889]
 [0.18639413 0.32969605 0.20294862 0.57974655]
 [0.16290852 0.51546027 0.67387044 0.28775056]
 [0.24148955 0.30713445 0.23063071 0.18349053]
 [0.74825937 0.50995052 0.45672112 0.42253872]
 [0.43755829 0.97191881 0.25018268 0.5725189 ]
 [0.83270528 0.77206018 0.50895026 0.54271351]
 [0.18772037 0.27642649 0.7747942  0.73096974]
 [0.75819311 0.46402997 0.25589352 0.2301761 ]]


In [26]:
h=a[0:5,:]
print(h)

[[0.41069897 0.71261642 0.61297788 0.5940692 ]
 [0.60379663 0.21418231 0.9602965  0.65555889]
 [0.18639413 0.32969605 0.20294862 0.57974655]
 [0.16290852 0.51546027 0.67387044 0.28775056]
 [0.24148955 0.30713445 0.23063071 0.18349053]]


#### Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [27]:
x = np.arange(10)
print(x)
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[9 6 4 0 2 7 1 3 5 8]


#### Read an JPEG image into a numpy array, return the size and shap of that image

In [28]:
from PIL import Image # pillow module
from numpy import asarray # converting image to array
image = Image.open('kolala.jpg')
data = asarray(image)
print(type(data))
print(data.shape)
print(data.size)

FileNotFoundError: [Errno 2] No such file or directory: 'kolala.jpg'