In [3]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [4]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max= np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [5]:
# Not the proper way You should use return statement
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        print(x)
    else:
        print(y)

pair_max= np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

6
6
7
9
8
9
7
5


array([None, None, None, None, None, None, None], dtype=object)

In [6]:
!curl -o ex.ipynb https://raw.githubusercontent.com/sumathi16/numpy-100/master/100_Numpy_exercises_no_solution.ipynb

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--

In [7]:
import pandas as pd
pd.Series([1,2],index=["one","two"])

one    1
two    2
dtype: int64

In [8]:
!curl -o sample.csv https://raw.githubusercontent.com/MLakshmichandrakala/m.lakshmichandrakala/master/sample.csv


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
100   115  100   115    0     0     20      0  0:00:05  0:00:05 --:--:--    20
100   115  100   115    0     0     20      0  0:00:05  0:00:05 --:--:--    29


In [9]:
data = pd.read_csv("sample.csv")
data

name  salary  year
0       Raj acharya   45000  2015
1       SaiTeja Ram   78000  2012
2     Hemendra Arya   32000  2018
3  Revanth Sundaram   15000  2019

In [10]:
data = pd.read_csv("https://raw.githubusercontent.com/MLakshmichandrakala/m.lakshmichandrakala/master/sample.csv")
data

name  salary  year
0       Raj acharya   45000  2015
1       SaiTeja Ram   78000  2012
2     Hemendra Arya   32000  2018
3  Revanth Sundaram   15000  2019

In [11]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer: Union[str, pathlib.Path, IO[~AnyStr]], sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, dialect=None, error_bad_lines=True, warn_bad_lines=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read a comma-separated values (csv) file into Dat

In [12]:
data = pd.read_csv("sample.csv",header=None)
data

0       1     2
0              name  salary  year
1       Raj acharya   45000  2015
2       SaiTeja Ram   78000  2012
3     Hemendra Arya   32000  2018
4  Revanth Sundaram   15000  2019

In [13]:
data = pd.read_csv("samplewithoutnames.csv")
data

Raj Acharya    45000   2015
0      SaiTeja Ram     78000  2012
1      Hemendra Arya   32000  2018
2  Revanth Sundarm     15000  2019

In [14]:
data = pd.read_csv("samplewithoutnames.csv",header=None)
data

0      1     2
0      Raj Acharya    45000  2015
1      SaiTeja Ram    78000  2012
2      Hemendra Arya  32000  2018
3  Revanth Sundarm    15000  2019

In [15]:
data = pd.read_csv("samplewithoutnames.csv",header=None,names=['name','salary','year'])
data

name  salary  year
0      Raj Acharya     45000  2015
1      SaiTeja Ram     78000  2012
2      Hemendra Arya   32000  2018
3  Revanth Sundarm     15000  2019

In [39]:
data = pd.read_csv("sample.tsv",sep='\t')
data

names  salary  year
0      Raj Acharya  45000  2015
1     SaiTeja Ram  78000   2012
2   Hemendra Arya  32000   2018
3  Revanth Sundarm  15000  2019

In [41]:
data = pd.read_csv("sample.tsv1",sep='\t',usecols=["names"])
data

names
0       Raj Acharya 
1      SaiTeja Ram  
2    Hemendra Arya  
3  Revanth Sundarm

In [49]:
data = pd.read_csv("sample.tsv2",sep='\t',index_col =[2])
data

IndexError: list index out of range

In [51]:
FL_data = pd.read_csv("FL_insurance_sample.csv")
FL_data

policyID statecode           county  eq_site_limit  hu_site_limit  \
0        119736        FL      CLAY COUNTY       498960.0      498960.00   
1        448094        FL      CLAY COUNTY      1322376.3     1322376.30   
2        206893        FL      CLAY COUNTY       190724.4      190724.40   
3        333743        FL      CLAY COUNTY            0.0       79520.76   
4        172534        FL      CLAY COUNTY            0.0      254281.50   
...         ...       ...              ...            ...            ...   
36629    404309        FL  PINELLAS COUNTY            0.0       88722.00   
36630    465875        FL  PINELLAS COUNTY      1297057.5     1297057.50   
36631    791209        FL  PINELLAS COUNTY       173286.9      173286.90   
36632    322627        FL  PINELLAS COUNTY      1499781.6     1499781.60   
36633    398149        FL  PINELLAS COUNTY       373488.3      373488.30   

       fl_site_limit  fr_site_limit    tiv_2011    tiv_2012  \
0           498960.0       498960.0   498960.00   792148.90   
1          1322376.3      1322376.3  1322376.30  1438163.57   
2           190724.4       190724.4   190724.40   192476.78   
3                0.0            0.0    79520.76    86854.48   
4                0.0       254281.5   254281.50   246144.49   
...              ...            ...         ...         ...   
36629            0.0        88722.0    88722.00   155065.65   
36630      1297057.5      1297057.5  1297057.50  1577500.79   
36631            0.0            0.0   173286.90   205527.97   
36632            0.0            0.0  1499781.60  1768782.43   
36633            0.0            0.0   373488.30   596003.67   

       eq_site_deductible  hu_site_deductible  fl_site_deductible  \
0                     0.0              9979.2                 0.0   
1                     0.0                 0.0                 0.0   
2                     0.0                 0.0                 0.0   
3                     0.0                 0.0                 0.0   
4                     0.0                 0.0                 0.0   
...                   ...                 ...                 ...   
36629                 0.0                 0.0                 0.0   
36630                 0.0                 0.0                 0.0   
36631                 0.0                 0.0                 0.0   
36632                 0.0                 0.0                 0.0   
36633                 0.0                 0.0                 0.0   

       fr_site_deductible  point_latitude  point_longitude         line  \
0                       0       30.102261       -81.711777  Residential   
1                       0       30.063936       -81.707664  Residential   
2                       0       30.089579       -81.700455  Residential   
3                       0       30.063236       -81.707703  Residential   
4                       0       30.060614       -81.702675  Residential   
...                   ...             ...              ...          ...   
36629                   0       28.122885       -82.770218  Residential   
36630                   0       28.080900       -82.758800  Residential   
36631                   0       28.110550       -82.766360  Residential   
36632                   0       28.089415       -82.697411  Residential   
36633                   0       28.064440       -82.774590  Residential   

      construction  point_granularity  
0          Masonry                  1  
1          Masonry                  3  
2             Wood                  1  
3             Wood                  3  
4             Wood                  1  
...            ...                ...  
36629         Wood                  3  
36630      Masonry                  1  
36631         Wood                  4  
36632      Masonry                  3  
36633      Masonry                  1  

[36634 rows x 18 columns]

In [52]:
print(FL_data.shape)
print(FL_data.shape[0])# No of rows
print(FL_data.shape[1]) # No of columns

(36634, 18)
36634
18


In [53]:
FL_data.columns

Index(['policyID', 'statecode', 'county', 'eq_site_limit', 'hu_site_limit',
       'fl_site_limit', 'fr_site_limit', 'tiv_2011', 'tiv_2012',
       'eq_site_deductible', 'hu_site_deductible', 'fl_site_deductible',
       'fr_site_deductible', 'point_latitude', 'point_longitude', 'line',
       'construction', 'point_granularity'],
      dtype='object')

In [54]:
FL_data.index

RangeIndex(start=0, stop=36634, step=1)

In [55]:

FL_data.policyID

0        119736
1        448094
2        206893
3        333743
4        172534
          ...  
36629    404309
36630    465875
36631    791209
36632    322627
36633    398149
Name: policyID, Length: 36634, dtype: int64

In [56]:
FL_data['policyID']

0        119736
1        448094
2        206893
3        333743
4        172534
          ...  
36629    404309
36630    465875
36631    791209
36632    322627
36633    398149
Name: policyID, Length: 36634, dtype: int64

In [57]:
print(type(FL_data['policyID']))

<class 'pandas.core.series.Series'>


In [58]:
FL_data[['policyID']]

policyID
0        119736
1        448094
2        206893
3        333743
4        172534
...         ...
36629    404309
36630    465875
36631    791209
36632    322627
36633    398149

[36634 rows x 1 columns]

In [59]:
FL_data[['policyID','statecode']]

policyID statecode
0        119736        FL
1        448094        FL
2        206893        FL
3        333743        FL
4        172534        FL
...         ...       ...
36629    404309        FL
36630    465875        FL
36631    791209        FL
36632    322627        FL
36633    398149        FL

[36634 rows x 2 columns]

In [60]:

FL_data[['statecode','policyID']]

statecode  policyID
0            FL    119736
1            FL    448094
2            FL    206893
3            FL    333743
4            FL    172534
...         ...       ...
36629        FL    404309
36630        FL    465875
36631        FL    791209
36632        FL    322627
36633        FL    398149

[36634 rows x 2 columns]

In [61]:
FL_data.head() # first 5 rows

policyID statecode       county  eq_site_limit  hu_site_limit  \
0    119736        FL  CLAY COUNTY       498960.0      498960.00   
1    448094        FL  CLAY COUNTY      1322376.3     1322376.30   
2    206893        FL  CLAY COUNTY       190724.4      190724.40   
3    333743        FL  CLAY COUNTY            0.0       79520.76   
4    172534        FL  CLAY COUNTY            0.0      254281.50   

   fl_site_limit  fr_site_limit    tiv_2011    tiv_2012  eq_site_deductible  \
0       498960.0       498960.0   498960.00   792148.90                 0.0   
1      1322376.3      1322376.3  1322376.30  1438163.57                 0.0   
2       190724.4       190724.4   190724.40   192476.78                 0.0   
3            0.0            0.0    79520.76    86854.48                 0.0   
4            0.0       254281.5   254281.50   246144.49                 0.0   

   hu_site_deductible  fl_site_deductible  fr_site_deductible  point_latitude  \
0              9979.2                 0.0                   0       30.102261   
1                 0.0                 0.0                   0       30.063936   
2                 0.0                 0.0                   0       30.089579   
3                 0.0                 0.0                   0       30.063236   
4                 0.0                 0.0                   0       30.060614   

   point_longitude         line construction  point_granularity  
0       -81.711777  Residential      Masonry                  1  
1       -81.707664  Residential      Masonry                  3  
2       -81.700455  Residential         Wood                  1  
3       -81.707703  Residential         Wood                  3  
4       -81.702675  Residential         Wood                  1

In [62]:

FL_data.head(2)

policyID statecode       county  eq_site_limit  hu_site_limit  \
0    119736        FL  CLAY COUNTY       498960.0       498960.0   
1    448094        FL  CLAY COUNTY      1322376.3      1322376.3   

   fl_site_limit  fr_site_limit   tiv_2011    tiv_2012  eq_site_deductible  \
0       498960.0       498960.0   498960.0   792148.90                 0.0   
1      1322376.3      1322376.3  1322376.3  1438163.57                 0.0   

   hu_site_deductible  fl_site_deductible  fr_site_deductible  point_latitude  \
0              9979.2                 0.0                   0       30.102261   
1                 0.0                 0.0                   0       30.063936   

   point_longitude         line construction  point_granularity  
0       -81.711777  Residential      Masonry                  1  
1       -81.707664  Residential      Masonry                  3

In [63]:
FL_data.tail()

policyID statecode           county  eq_site_limit  hu_site_limit  \
36629    404309        FL  PINELLAS COUNTY            0.0        88722.0   
36630    465875        FL  PINELLAS COUNTY      1297057.5      1297057.5   
36631    791209        FL  PINELLAS COUNTY       173286.9       173286.9   
36632    322627        FL  PINELLAS COUNTY      1499781.6      1499781.6   
36633    398149        FL  PINELLAS COUNTY       373488.3       373488.3   

       fl_site_limit  fr_site_limit   tiv_2011    tiv_2012  \
36629            0.0        88722.0    88722.0   155065.65   
36630      1297057.5      1297057.5  1297057.5  1577500.79   
36631            0.0            0.0   173286.9   205527.97   
36632            0.0            0.0  1499781.6  1768782.43   
36633            0.0            0.0   373488.3   596003.67   

       eq_site_deductible  hu_site_deductible  fl_site_deductible  \
36629                 0.0                 0.0                 0.0   
36630                 0.0                 0.0                 0.0   
36631                 0.0                 0.0                 0.0   
36632                 0.0                 0.0                 0.0   
36633                 0.0                 0.0                 0.0   

       fr_site_deductible  point_latitude  point_longitude         line  \
36629                   0       28.122885       -82.770218  Residential   
36630                   0       28.080900       -82.758800  Residential   
36631                   0       28.110550       -82.766360  Residential   
36632                   0       28.089415       -82.697411  Residential   
36633                   0       28.064440       -82.774590  Residential   

      construction  point_granularity  
36629         Wood                  3  
36630      Masonry                  1  
36631         Wood                  4  
36632      Masonry                  3  
36633      Masonry                  1

In [64]:
FL_data.tail(3)

policyID statecode           county  eq_site_limit  hu_site_limit  \
36631    791209        FL  PINELLAS COUNTY       173286.9       173286.9   
36632    322627        FL  PINELLAS COUNTY      1499781.6      1499781.6   
36633    398149        FL  PINELLAS COUNTY       373488.3       373488.3   

       fl_site_limit  fr_site_limit   tiv_2011    tiv_2012  \
36631            0.0            0.0   173286.9   205527.97   
36632            0.0            0.0  1499781.6  1768782.43   
36633            0.0            0.0   373488.3   596003.67   

       eq_site_deductible  hu_site_deductible  fl_site_deductible  \
36631                 0.0                 0.0                 0.0   
36632                 0.0                 0.0                 0.0   
36633                 0.0                 0.0                 0.0   

       fr_site_deductible  point_latitude  point_longitude         line  \
36631                   0       28.110550       -82.766360  Residential   
36632                   0       28.089415       -82.697411  Residential   
36633                   0       28.064440       -82.774590  Residential   

      construction  point_granularity  
36631         Wood                  4  
36632      Masonry                  3  
36633      Masonry                  1

In [65]:
FL_data.sample(4)

policyID statecode           county  eq_site_limit  hu_site_limit  \
14944    128468        FL   BREVARD COUNTY            0.0      588506.14   
32586    461396        FL   COLLIER COUNTY            0.0      344368.93   
12134    175264        FL  SEMINOLE COUNTY            0.0       39413.17   
34342    109200        FL  SARASOTA COUNTY            0.0     3434477.71   

       fl_site_limit  fr_site_limit    tiv_2011    tiv_2012  \
14944            0.0            0.0   588506.14   464428.45   
32586            0.0            0.0   344368.93   425285.29   
12134            0.0            0.0    39413.17    42422.36   
34342            0.0            0.0  3434477.71  4806345.49   

       eq_site_deductible  hu_site_deductible  fl_site_deductible  \
14944                 0.0                 0.0                 0.0   
32586                 0.0                 0.0                 0.0   
12134                 0.0                 0.0                 0.0   
34342                 0.0                 0.0                 0.0   

       fr_site_deductible  point_latitude  point_longitude         line  \
14944                   0       28.109791       -80.649849  Residential   
32586                   0       26.151865       -81.794762  Residential   
12134                   0       28.802578       -81.391190  Residential   
34342                   0       27.137407       -82.400978   Commercial   

             construction  point_granularity  
14944             Masonry                  4  
32586                Wood                  3  
12134                Wood                  1  
34342  Reinforced Masonry                  1

In [66]:
FL_data.sample()

policyID statecode        county  eq_site_limit  hu_site_limit  \
3491    387611        FL  DUVAL COUNTY            0.0      214644.01   

      fl_site_limit  fr_site_limit   tiv_2011   tiv_2012  eq_site_deductible  \
3491            0.0            0.0  214644.01  221193.87                 0.0   

      hu_site_deductible  fl_site_deductible  fr_site_deductible  \
3491                 0.0                 0.0                   0   

      point_latitude  point_longitude         line construction  \
3491        30.29621       -81.653235  Residential         Wood   

      point_granularity  
3491                  3

In [67]:
data = pd.read_csv("sample.csv")

In [68]:
data

name  salary  year
0       Raj acharya   45000  2015
1       SaiTeja Ram   78000  2012
2     Hemendra Arya   32000  2018
3  Revanth Sundaram   15000  2019

In [69]:
FL_data.dtypes

policyID                int64
statecode              object
county                 object
eq_site_limit         float64
hu_site_limit         float64
fl_site_limit         float64
fr_site_limit         float64
tiv_2011              float64
tiv_2012              float64
eq_site_deductible    float64
hu_site_deductible    float64
fl_site_deductible    float64
fr_site_deductible      int64
point_latitude        float64
point_longitude       float64
line                   object
construction           object
point_granularity       int64
dtype: object

In [70]:
FL_data.policyID.dtype

dtype('int64')

In [71]:
FL_data.dtypes[0],FL_data.dtypes["policyID"]

(dtype('int64'), dtype('int64'))

In [72]:
FL_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36634 entries, 0 to 36633
Data columns (total 18 columns):
policyID              36634 non-null int64
statecode             36634 non-null object
county                36634 non-null object
eq_site_limit         36634 non-null float64
hu_site_limit         36634 non-null float64
fl_site_limit         36634 non-null float64
fr_site_limit         36634 non-null float64
tiv_2011              36634 non-null float64
tiv_2012              36634 non-null float64
eq_site_deductible    36634 non-null float64
hu_site_deductible    36634 non-null float64
fl_site_deductible    36634 non-null float64
fr_site_deductible    36634 non-null int64
point_latitude        36634 non-null float64
point_longitude       36634 non-null float64
line                  36634 non-null object
construction          36634 non-null object
point_granularity     36634 non-null int64
dtypes: float64(11), int64(3), object(4)
memory usage: 5.0+ MB


In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
name      4 non-null object
salary    4 non-null int64
year      4 non-null int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [74]:
FL_data.dtypes.value_counts()

float64    11
object      4
int64       3
dtype: int64

In [75]:
FL_data.dtypes.value_counts()[0]

11

In [76]:
type(FL_data.dtypes.value_counts().index[0])

numpy.dtype

In [77]:
type(np.float64)

type

In [78]:
FL_data.dtypes

policyID                int64
statecode              object
county                 object
eq_site_limit         float64
hu_site_limit         float64
fl_site_limit         float64
fr_site_limit         float64
tiv_2011              float64
tiv_2012              float64
eq_site_deductible    float64
hu_site_deductible    float64
fl_site_deductible    float64
fr_site_deductible      int64
point_latitude        float64
point_longitude       float64
line                   object
construction           object
point_granularity       int64
dtype: object

In [79]:
FL_data.dtypes==np.int64

policyID               True
statecode             False
county                False
eq_site_limit         False
hu_site_limit         False
fl_site_limit         False
fr_site_limit         False
tiv_2011              False
tiv_2012              False
eq_site_deductible    False
hu_site_deductible    False
fl_site_deductible    False
fr_site_deductible     True
point_latitude        False
point_longitude       False
line                  False
construction          False
point_granularity      True
dtype: bool

In [80]:
FL_data.dtypes[FL_data.dtypes==np.int64]

policyID              int64
fr_site_deductible    int64
point_granularity     int64
dtype: object

In [81]:
FL_data.columns[FL_data.dtypes==np.int64]

Index(['policyID', 'fr_site_deductible', 'point_granularity'], dtype='object')